apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iletken.fullname" . }}-config
  labels:
    {{- include "iletken.labels" . | nindent 4 }}
data:
  iletken.yml: |
    server:
      host: "0.0.0.0"
      port: 8080
      read_timeout: "60s"
      write_timeout: "60s"
      idle_timeout: "60s"

    {{- if .Values.redirects }}
    redirects:
      {{- range .Values.redirects }}
      - from: {{ .from | quote }}
        to: {{ .to | quote }}
      {{- end }}
    {{- end }}

    logging:
      level: "info"
      format: "json"
